### ISSUE TITLE
Can't see any audio devices

### ISSUE THREAD

**Issue by alexstojda** [melchor629/chromecaster-gui#6]
The application doesn't list any audio devices to cast, I just get a blank select list. 

System: Windows 10 64-bit

**Comment by melchor629** [comment]
Sad to hear that :(

It is possible that your problems is due the third party library [portaudio](http://www.portaudio.com/download.html). Check [this page from Audacity](https://wiki.audacityteam.org/wiki/Windows_10_OS#Sound_Device_driver_requirements_and_problems), maybe it helps. Audacity uses portaudio too - _maybe you can check if Audacity is working well or it is failing too_. As I saw googling, some drivers could lead into portaudio failure, so check that the drivers are updated and are 64-bit versions.

Hope it helps :)

**Comment by jerblack** [comment]
I'm having the same issue. Which sucks because I just tried 3 other apps and yours is the only one that can see a cast group. It just doesn't see my audio device.

**Comment by alexstojda** [comment]
Went through all of the troubleshooting in audacity with no luck, the application still can't see my audio devices. 

@melchor629  have you tested this on windows 10 64-bit systems? Whats your audio setup like? Do you have additional software running like Realtek audio manager?

**Comment by melchor629** [comment]
Hi all. My testing environment is, in general, a VMWare VM of Windows 10 64bit. But, time to time, I check in a real Windows 10 (also 64 bit) with the latest, or at least a very recently, Windows updates. Is a MacBook Pro with the Apple drivers (sound card is a Cirrus Logic). They don't provide anything like an "control center" as Realtek usually does. In the MBP, the audio devices show up, using the latest version in GitHub.

> Note: _I had to make a quick fix when I release 1.0.4 so maybe you had the version with the failure_

I should investigate more about this issue, but as I cannot reproduce the issue, will be difficult. I will tell you something shortly.

**Comment by melchor629** [comment]
@alexstojda @jerblack can both of you try executing Chromecaster from a PowerShell?

Steps I did to execute from PowerShell:

 - use the zip Windows version and extract it
 - Enter in the extracted folder with File Explorer
 - Shift + Right Click without selecting a file/folder and in the options you will see something like "Open a PowerShell window here"
 - With the PowerShell opened, write `.\Chromecaster.exe` (or write `Chro` and press TAB for laziness)

Doing this, will print logs on the PowerShell. I would like to have your logs. If you can paste them here (or in a gist or pastebin...). See if I could find the issues with the logs.

_It could work with CMD too, but I didn't try. Having PowerShell :)_

**Comment by Onset** [comment]
I see my Chromecast (video) only. Two Chromecasts audio in network are missing and group they are in too.

**Comment by Onset** [comment]
I don't se any devices. I have a Chromecast video, two audios and a group.

![image](https://user-images.githubusercontent.com/1045362/45577113-ae06c400-b87a-11e8-87dc-1d4ca3ab8d0b.png)

Power shell output: (I suspect missing Squirrel)
```
PS C:\Users\chalu\Desktop\Chromecaster-1.0.4-win>
Error: Can not find Squirrel
    at AutoUpdater.emitError (C:\Users\chalu\Desktop\Chromecaster-1.0.4-win\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:58:24)
    at AutoUpdater.checkForUpdates (C:\Users\chalu\Desktop\Chromecaster-1.0.4-win\resources\electron.asar\browser\api\auto-updater\auto-updater-win.js:29:19)
    at Object.<anonymous> (C:\Users\chalu\Desktop\Chromecaster-1.0.4-win\resources\app.asar\updater.js:17:17)
    at Object.<anonymous> (C:\Users\chalu\Desktop\Chromecaster-1.0.4-win\resources\app.asar\updater.js:20:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
Loading libFLAC from resources
Loading libportaudio from resources
before paHostApiInitializers[0].
after paHostApiInitializers[0].
before paHostApiInitializers[1].
WASAPI: device idx: 00
WASAPI: ---------------
WASAPI:0| name[Speakers (Realtek High Definition Audio)]
WASAPI:0| form-factor[1]
WASAPI: getting Windows version with GetVersion()
WASAPI: Windows version = 5
WASAPI: IAudioClient version = 2
WASAPI:0| def.SR[48000] max.CH[2] latency{hi[0.010000] lo[0.003000]}
WASAPI: device idx: 01
WASAPI: ---------------
WASAPI:1| name[CF791 (Intel(R) Display Audio)]
WASAPI:1| form-factor[9]
WASAPI:1| def.SR[48000] max.CH[2] latency{hi[0.010000] lo[0.003000]}
WASAPI: device idx: 02
WASAPI: ---------------
WASAPI:2| name[Microphone (Realtek High Definition Audio)]
WASAPI:2| form-factor[4]
WASAPI:2| def.SR[48000] max.CH[2] latency{hi[0.010000] lo[0.003000]}
WASAPI: initialized ok
after paHostApiInitializers[1].
before paHostApiInitializers[2].
Setup called
Enum called
noError = 1
Device 0 has render alias
Enum called
noError = 0
Enum called
noError = 0
Enum called
noError = 0
Device 3 has capture alias
Enum called
noError = 0
Device 4 has capture alias
Enum called
noError = 0
Enum called
noError = 1
Device 6 has render alias
Enum called
noError = 0
Enum called
Interfaces found: 4
Device 0 has render alias
Device 0 has realtime alias
Interface 0, Name: R
FilterNew: Creating filter 'Realtek HD Audio output'
FilterNew: Opening filter...
DumpConnectionsAndNodes: connections=2, nodes=1
  Connection: 0 - FromNode=4294967295,FromPin=0 -> ToNode=0,ToPin=1
  Connection: 1 - FromNode=0,FromPin=0 -> ToNode=4294967295,ToPin=1
  Node: 0 - {507AE360-C554-11D0-8A2B-00A0C9255AC1}
PinNew: Creating pin 0:
PinNew: Checking 1 no of dataranges...
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Format PCM 24 bit supported
PinNew: Format PCM 32 bit supported
PinNew: Default sample rate = 44100 Hz
Failed PinQueryNotificationSupport
PinNew: Finding topology pin...
FindStartConnectionTo: Startpin 0, Checking 2 connections...
FindStartConnectionTo: returning 000002B55380D188
GetConnectedPin: count=1, forward=1, muxPosition=-1
GetConnectionTo: Checking 2 connections... (pFrom = 000002B55380D188)GetConnectionTo: Returning 000002B55380D198
PinNew: Getting physical connection...
PinNew: Physical connection found!
PinNew: Creating topology filter '\\?\HDAUDIO#FUNC_01&VEN_10EC&DEV_0255&SUBSYS_104312D0&REV_1000#4&14ee12b8&0&0001#{6994ad04-93ef-11d0-a3cc-00a0c9223196}\SingleLineOutTopo'
FilterNew: Creating filter ''
FilterNew: Opening filter...
DumpConnectionsAndNodes: connections=3, nodes=2
  Connection: 0 - FromNode=4294967295,FromPin=0 -> ToNode=0,ToPin=1
  Connection: 1 - FromNode=0,FromPin=0 -> ToNode=1,ToPin=1
  Connection: 2 - FromNode=1,FromPin=0 -> ToNode=4294967295,ToPin=1
  Node: 0 - {3A5ACC00-C557-11D0-8A2B-00A0C9255AC1}
  Node: 1 - {02B223C0-C557-11D0-8A2B-00A0C9255AC1}
PinNew: Opening topology filter...PinNew: Checking for output endpoint pin id...
FindStartConnectionTo: Startpin 0, Checking 3 connections...
FindStartConnectionTo: returning 000002B55388B408
GetConnectedPin: count=2, forward=1, muxPosition=-1
GetConnectionTo: Checking 3 connections... (pFrom = 000002B55388B408)GetConnectionTo: Returning 000002B55388B418
GetConnectedPin: count=2, forward=1, muxPosition=-1
GetConnectionTo: Checking 3 connections... (pFrom = 000002B55388B418)GetConnectionTo: Returning 000002B55388B428
PinNew: Found endpoint pin id 1
GetNameFromCategory: USB GUID 0301 -> 'Speakers'
PinNew: Pin name 'Speakers'
PinNew: Releasing topology filter...
Pin created successfully
PinNew: Creating pin 1:
PinNew: Not source/sink
PinNew: Error -9996
Filter (WaveRT) created with 1 valid pins (total I/Os: 1)
Device 3 has capture alias
Device 3 has realtime alias
Interface 3, Name: R
FilterNew: Creating filter 'Realtek HD Audio Mic input'
FilterNew: Opening filter...
DumpConnectionsAndNodes: connections=2, nodes=1
  Connection: 0 - FromNode=4294967295,FromPin=1 -> ToNode=0,ToPin=1
  Connection: 1 - FromNode=0,FromPin=0 -> ToNode=4294967295,ToPin=0
  Node: 0 - {4D837FE0-C555-11D0-8A2B-00A0C9255AC1}
PinNew: Creating pin 0:
PinNew: Checking 1 no of dataranges...
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Default sample rate = 44100 Hz
Failed PinQueryNotificationSupport
PinNew: Finding topology pin...
FindStartConnectionFrom: Startpin 0, Checking 2 connections...
FindStartConnectionFrom: returning 000002B55380CD48
GetConnectedPin: count=1, forward=0, muxPosition=-1
GetConnectionFrom: Checking 2 connections... (pTo = 000002B55380CD48)
GetConnectionFrom: Returning 000002B55380CD38
PinNew: Getting physical connection...
PinNew: Physical connection found!
PinNew: Creating topology filter '\\?\HDAUDIO#FUNC_01&VEN_10EC&DEV_0255&SUBSYS_104312D0&REV_1000#4&14ee12b8&0&0001#{6994ad04-93ef-11d0-a3cc-00a0c9223196}\RtMicInTopo'
FilterNew: Creating filter ''
FilterNew: Opening filter...
DumpConnectionsAndNodes: connections=4, nodes=3
  Connection: 0 - FromNode=4294967295,FromPin=1 -> ToNode=0,ToPin=1
  Connection: 1 - FromNode=0,FromPin=0 -> ToNode=2,ToPin=1
  Connection: 2 - FromNode=2,FromPin=0 -> ToNode=1,ToPin=1
  Connection: 3 - FromNode=1,FromPin=0 -> ToNode=4294967295,ToPin=0
  Node: 0 - {3A5ACC00-C557-11D0-8A2B-00A0C9255AC1}
  Node: 1 - {3A5ACC00-C557-11D0-8A2B-00A0C9255AC1}
  Node: 2 - {02B223C0-C557-11D0-8A2B-00A0C9255AC1}
PinNew: Opening topology filter...PinNew: Checking for input endpoint pin id (0)...
FindStartConnectionFrom: Startpin 0, Checking 4 connections...
FindStartConnectionFrom: returning 000002B55381B838
GetConnectedPin: count=3, forward=0, muxPosition=0
GetConnectionFrom: Checking 4 connections... (pTo = 000002B55381B838)
GetConnectionFrom: Returning 000002B55381B828
GetConnectedPin: count=3, forward=0, muxPosition=0
GetConnectionFrom: Checking 4 connections... (pTo = 000002B55381B828)
GetConnectionFrom: Returning 000002B55381B818
GetConnectedPin: count=3, forward=0, muxPosition=0
GetConnectionFrom: Checking 4 connections... (pTo = 000002B55381B818)
GetConnectionFrom: Returning 000002B55381B808
PinNew: Found endpoint pin id 1
PinNew: Input friendly name 'Microphone'
PinNew: Releasing topology filter...
Pin created successfully
PinNew: Creating pin 1:
PinNew: Not source/sink
PinNew: Error -9996
Filter (WaveRT) created with 1 valid pins (total I/Os: 1)
Device 4 has capture alias
Device 4 has realtime alias
Interface 4, Name: R
FilterNew: Creating filter 'Realtek HD Audio Stereo input'
FilterNew: Opening filter...
DumpConnectionsAndNodes: connections=2, nodes=1
  Connection: 0 - FromNode=4294967295,FromPin=1 -> ToNode=0,ToPin=1
  Connection: 1 - FromNode=0,FromPin=0 -> ToNode=4294967295,ToPin=0
  Node: 0 - {4D837FE0-C555-11D0-8A2B-00A0C9255AC1}
PinNew: Creating pin 0:
PinNew: Checking 1 no of dataranges...
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Default sample rate = 48000 Hz
Failed PinQueryNotificationSupport
PinNew: Finding topology pin...
FindStartConnectionFrom: Startpin 0, Checking 2 connections...
FindStartConnectionFrom: returning 000002B55380D438
GetConnectedPin: count=1, forward=0, muxPosition=-1
GetConnectionFrom: Checking 2 connections... (pTo = 000002B55380D438)
GetConnectionFrom: Returning 000002B55380D428
PinNew: Getting physical connection...
PinNew: Physical connection found!
PinNew: Creating topology filter '\\?\HDAUDIO#FUNC_01&VEN_10EC&DEV_0255&SUBSYS_104312D0&REV_1000#4&14ee12b8&0&0001#{6994ad04-93ef-11d0-a3cc-00a0c9223196}\RtStereoMixTopo'
FilterNew: Creating filter ''
FilterNew: Opening filter...
DumpConnectionsAndNodes: connections=3, nodes=2
  Connection: 0 - FromNode=4294967295,FromPin=1 -> ToNode=1,ToPin=1
  Connection: 1 - FromNode=1,FromPin=0 -> ToNode=0,ToPin=1
  Connection: 2 - FromNode=0,FromPin=0 -> ToNode=4294967295,ToPin=0
  Node: 0 - {3A5ACC00-C557-11D0-8A2B-00A0C9255AC1}
  Node: 1 - {02B223C0-C557-11D0-8A2B-00A0C9255AC1}
PinNew: Opening topology filter...PinNew: Checking for input endpoint pin id (0)...
FindStartConnectionFrom: Startpin 0, Checking 3 connections...
FindStartConnectionFrom: returning 000002B55388A9E8
GetConnectedPin: count=2, forward=0, muxPosition=0
GetConnectionFrom: Checking 3 connections... (pTo = 000002B55388A9E8)
GetConnectionFrom: Returning 000002B55388A9D8
GetConnectedPin: count=2, forward=0, muxPosition=0
GetConnectionFrom: Checking 3 connections... (pTo = 000002B55388A9D8)
GetConnectionFrom: Returning 000002B55388A9C8
PinNew: Found endpoint pin id 1
PinNew: Input friendly name 'Stereo Mix'
PinNew: Releasing topology filter...
Pin created successfully
PinNew: Creating pin 1:
PinNew: Not source/sink
PinNew: Error -9996
Filter (WaveRT) created with 1 valid pins (total I/Os: 1)
Device 6 has render alias
Device 6 has realtime alias
Interface 6, Name: I
FilterNew: Creating filter 'Intel(R) Display Audio Output 2'
FilterNew: Opening filter...
DumpConnectionsAndNodes: connections=2, nodes=1
  Connection: 0 - FromNode=4294967295,FromPin=0 -> ToNode=0,ToPin=1
  Connection: 1 - FromNode=0,FromPin=0 -> ToNode=4294967295,ToPin=1
  Node: 0 - {D1B9CC2A-F519-417F-91C9-55FA65481001}
PinNew: Creating pin 0:
PinNew: Checking 6 no of dataranges...
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Format PCM 24 bit supported
PinNew: Format PCM 32 bit supported
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Format PCM 24 bit supported
PinNew: Format PCM 32 bit supported
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Format PCM 24 bit supported
PinNew: Format PCM 32 bit supported
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Format PCM 24 bit supported
PinNew: Format PCM 32 bit supported
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Format PCM 24 bit supported
PinNew: Format PCM 32 bit supported
PinNew: DR major format 73647561
PinNew: MaxChannel: 2
PinNew: Format PCM 16 bit supported
PinNew: Format PCM 24 bit supported
PinNew: Format PCM 32 bit supported
PinNew: Default sample rate = 44100 Hz
Failed PinQueryNotificationSupport
PinNew: Finding topology pin...
FindStartConnectionTo: Startpin 0, Checking 2 connections...
FindStartConnectionTo: returning 000002B55380CD68
GetConnectedPin: count=1, forward=1, muxPosition=-1
GetConnectionTo: Checking 2 connections... (pFrom = 000002B55380CD68)GetConnectionTo: Returning 000002B55380CD78
PinNew: Getting physical connection...
PinNew: Physical connection found!
PinNew: Creating topology filter '\\?\HDAUDIO#FUNC_01&VEN_8086&DEV_2809&SUBSYS_80860101&REV_1000#4&14ee12b8&0&0201#{6994ad04-93ef-11d0-a3cc-00a0c9223196}\IntcDAudLegacyTopo_2_48_24_D1'
FilterNew: Creating filter ''
FilterNew: Opening filter...
DumpConnectionsAndNodes: connections=3, nodes=2
  Connection: 0 - FromNode=4294967295,FromPin=0 -> ToNode=0,ToPin=1
  Connection: 1 - FromNode=0,FromPin=0 -> ToNode=1,ToPin=1
  Connection: 2 - FromNode=1,FromPin=0 -> ToNode=4294967295,ToPin=1
  Node: 0 - {02B223C0-C557-11D0-8A2B-00A0C9255AC1}
  Node: 1 - {941C7AC0-C559-11D0-8A2B-00A0C9255AC1}
PinNew: Opening topology filter...PinNew: Checking for output endpoint pin id...
FindStartConnectionTo: Startpin 0, Checking 3 connections...
FindStartConnectionTo: returning 000002B55388AA48
GetConnectedPin: count=2, forward=1, muxPosition=-1
GetConnectionTo: Checking 3 connections... (pFrom = 000002B55388AA48)GetConnectionTo: Returning 000002B55388AA58
GetConnectedPin: count=2, forward=1, muxPosition=-1
GetConnectionTo: Checking 3 connections... (pFrom = 000002B55388AA58)GetConnectionTo: Returning 000002B55388AA68
PinNew: Found endpoint pin id 1
PinNew: Pin name 'Output'
PinNew: Releasing topology filter...
Pin created successfully
PinNew: Creating pin 1:
PinNew: Not source/sink
PinNew: Error -9996
Filter (WaveRT) created with 1 valid pins (total I/Os: 1)
after paHostApiInitializers[2].
config:get selectedAudioDevice
config:get showWindow
config:get selectedQuality
config:reply:selectedAudioDevice [MME] Microsoft Sound Mapper - Input
config:reply:showWindow true
config:reply:selectedQuality 320
discoverChromecasts called
discoverChromecasts:end sent
```

**Comment by Onset** [comment]
Google Chrome Tab casting can see the Chromecast video though.

**Comment by alexstojda** [comment]
Closing this issue since I don't use the application at the moment and another issue was opened.

**Comment by dharmendrachauhan** [comment]
could you please share the download link I can't download it.
better if you can upload on google drive and share the link please
I'm using Google home and want to cast my PC Audio to my google home speaker..
Using windows 10 pro
