### ISSUE TITLE
Unexpected error when casting to Google Home

### ISSUE THREAD

**Issue by melchor629** [melchor629/chromecaster-gui#9]
![screenshot 2](https://user-images.githubusercontent.com/43657756/46837641-bbf52980-cdd3-11e8-968f-73fb8c59be7d.png)

This is the issue I'm getting could you please let me know what Audio input should be I tried everything it's not working.
I'm using google home and trying to cast my pc Audio to Google home 
Appreciate your work and time

_Originally posted by @dharmendrachauhan in https://github.com/melchor629/chromecaster-gui/commit/9ee90142563996cc3629e89e5df8f168ef21654d#commitcomment-30871372_

**Comment by melchor629** [comment]
Hi, try running the app from a PowerShell. You can do it by opening the PowerShell and _drag&drop_ the executable into it and then pressing enter. You will see the app running, but the PowerShell fill with a text. Do whatever you do to make it crash and then grab that text (from the PowerShell) and paste it here or in a gist. This will be useful to know what is going on under the hood.

**Comment by melchor629** [comment]
![screenshot 3](https://user-images.githubusercontent.com/43657756/46863977-93eae200-ce36-11e8-90c0-0a80a59863fc.png)
i tried using powershell same issue please have a look. 

config:reply:selectedAudioDevice [Windows WDM-KS] Stereo Mix (Realtek HD Audio Stereo input)
config:reply:selectedQuality 128
connectChromecast called with args: 'Dining room Speaker', '[Windows WDM-KS] Stereo Mix (Realtek HD Audio Stereo input)', '128'
discoverChromecasts:error sent with ("First search for a Chromecast")
discoverChromecasts called
discoverChromecasts:reply sent with {"addresses":["192.168.0.173"],"type":"Google Home Mini","name":"Dining room Speaker"}
connectChromecast called with args: 'Dining room Speaker', '[Windows WDM-KS] Stereo Mix (Realtek HD Audio Stereo input)', '128'
Pin:932137f0, DataRange:0
        FormatSize:88, SampleSize:0
        MaxChannels:2
        Bits:16-32
        SampleRate:48000-48000
Pin:932137f0, DataRange:0
        FormatSize:88, SampleSize:0
        MaxChannels:2
        Bits:16-32
        SampleRate:48000-48000
Error: Unsupported audio format
    at EventEmitter.electron.ipcMain.on.tt.connectChromecast (C:\Users\Dharmendra\Downloads\Compressed\Chromecaster-1.0.5-win\resources\app.asar\main.js:279:14)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (C:\Users\Dharmendra\Downloads\Compressed\Chromecaster-1.0.5-win\resources\electron.asar\browser\api\web-contents.js:286:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)

https://github.com/melchor629/chromecaster-gui/commit/9ee90142563996cc3629e89e5df8f168ef21654d#commitcomment-30877130

**Comment by melchor629** [comment]
It seems that with your current audio setup, the app cannot capture your internal audio (`Unsupported audio format`) and that's kind weird because the default configuration is basic enough that every computer should work out of the box (sample rate of 44100Hz and bit depth of 16bit).

Check if you can change the configuration of the internal audio device (look for it in the speaker icon in the task bar, at the left) to match these settings. It should be called "CD Quality" probably. But is a guess, it is a long time since I last used Windows...

Meanwhile, I will try to change the error message for one more clearer.

**Comment by dharmendrachauhan** [comment]
I'll check it and let you know Thanks for the reply. I really appreciate your time and efforts Thank you

**Comment by dharmendrachauhan** [comment]
I'm getting same error tried to change the input frequency and other stuff still same 
sharing what option i have 
![screenshot 4](https://user-images.githubusercontent.com/43657756/46895245-29b55a00-ce95-11e8-8706-81ecfc3b809e.png)

**Comment by melchor629** [comment]
I'm impressed with that, wow. I'm loosing all my ideas I have in this issue. I'm sorry to not be able to help you further more :(

I uploaded a new version that now shows an error instead of closing the app. Maybe it helps a bit. Try it and tell me what error you are getting or if it is still crashing.

One thing to note is that I use the same library as Audacity. So, if it goes well there, should go in my app. (If you don't know what app I'm talking about, is an open source multi-platform app for editing audio).

**Comment by melchor629** [comment]
About the Audacity, the issue has to do with the capturing audio from your computer (you can see the error in the latests lines of the PowerShell). This code is almost the same as Audacity, so if in Audacity works but not in my app, it will tell us that the issue is indeed in my code.

Well, you can always try to cast in other formats different from MP3 128 (like FLAC HD or WAV HD). 

Anyway, it seems to be an issue with my code, but as I cannot reproduce that, I'm not be able to fix it. I'm so sorry :(

Thanks for posting the issue and helping to solve it :)
